# Generated by Django 3.2 on 2021-04-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.AddField(
            model_name='post',
            name='popular',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
